// List<Map<dynamic, dynamic>> users = [
//   {
//     'name': 'Aarav Patel',
//     'email': 'aarav.patel@gmail.com',
//     'phone': 9876543210,
//     'dateOfBirth': '15-08-1990',
//     'gender': 1,
//     'city': 'Mumbai', // ✅ Added city
//     'hobbies': ['Reading', 'Traveling'],
//     'password': 'Aarav@123',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Ananya Sharma',
//     'email': 'ananya.sharma@yahoo.com',
//     'phone': 9123456789,
//     'dateOfBirth': '25-12-1985',
//     'gender': 0,
//     'city': 'Delhi', // ✅ Added city
//     'hobbies': ['Cooking', 'Dancing'],
//     'password': 'Ananya@456',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Rohan Kumar',
//     'email': 'rohan.kumar@outlook.com',
//     'phone': 9988776655,
//     'dateOfBirth': '10-06-2000',
//     'gender': 1,
//     'city': 'Bangalore', // ✅ Added city
//     'hobbies': ['Photography', 'Gaming'],
//     'password': 'Rohan#789',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Priya Reddy',
//     'email': 'priya.reddy@gmail.com',
//     'phone': 9123345567,
//     'dateOfBirth': '05-11-1995',
//     'gender': 0,
//     'city': 'Hyderabad', // ✅ Added city
//     'hobbies': ['Sports', 'Coding'],
//     'password': 'Priya@2023',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Vikram Singh',
//     'email': 'vikram.singh@hotmail.com',
//     'phone': 9234567810,
//     'dateOfBirth': '18-03-1992',
//     'gender': 1,
//     'city': 'Chandigarh', // ✅ Added city
//     'hobbies': ['Music', 'Drawing'],
//     'password': 'Vikram@321',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Neha Gupta',
//     'email': 'neha.gupta@gmail.com',
//     'phone': 9865432101,
//     'dateOfBirth': '30-09-1988',
//     'gender': 0,
//     'city': 'Jaipur', // ✅ Added city
//     'hobbies': ['Hiking', 'Blogging'],
//     'password': 'Neha@123',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Arjun Yadav',
//     'email': 'arjun.yadav@domain.com',
//     'phone': 9345678901,
//     'dateOfBirth': '22-07-1978',
//     'gender': 1,
//     'city': 'Lucknow', // ✅ Added city
//     'hobbies': ['Gardening', 'Fishing'],
//     'password': 'Arjun*456',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Sanya Desai',
//     'email': 'sanya.desai@domain.com',
//     'phone': 9876504321,
//     'dateOfBirth': '12-01-1993',
//     'gender': 0,
//     'city': 'Ahmedabad', // ✅ Added city
//     'hobbies': ['Yoga', 'Swimming'],
//     'password': 'Sanya#789',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Karan Mehta',
//     'email': 'karan.mehta@domain.com',
//     'phone': 9876512340,
//     'dateOfBirth': '05-05-2001',
//     'gender': 1,
//     'city': 'Pune', // ✅ Added city
//     'hobbies': ['Traveling', 'Photography'],
//     'password': 'Karan@890',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Simran Kaur',
//     'email': 'simran.kaur@domain.com',
//     'phone': 9123450987,
//     'dateOfBirth': '15-10-1997',
//     'gender': 0,
//     'city': 'Amritsar', // ✅ Added city
//     'hobbies': ['Writing', 'Crafting'],
//     'password': 'Simran@321',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Amit Verma',
//     'email': 'amit.verma@gmail.com',
//     'phone': 9234509876,
//     'dateOfBirth': '02-02-1990',
//     'gender': 1,
//     'city': 'Indore', // ✅ Added city
//     'hobbies': ['Cricket', 'Photography'],
//     'password': 'Amit@123',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Isha Rao',
//     'email': 'isha.rao@gmail.com',
//     'phone': 9345671234,
//     'dateOfBirth': '20-03-1987',
//     'gender': 0,
//     'city': 'Bhopal', // ✅ Added city
//     'hobbies': ['Writing', 'Painting'],
//     'password': 'Isha@456',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Suresh Babu',
//     'email': 'suresh.babu@outlook.com',
//     'phone': 9567894321,
//     'dateOfBirth': '10-11-1995',
//     'gender': 1,
//     'city': 'Chennai', // ✅ Added city
//     'hobbies': ['Music', 'Sports'],
//     'password': 'Suresh@789',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Maya Patel',
//     'email': 'maya.patel@gmail.com',
//     'phone': 9876123456,
//     'dateOfBirth': '05-06-1992',
//     'gender': 0,
//     'city': 'Surat', // ✅ Added city
//     'hobbies': ['Cooking', 'Traveling'],
//     'password': 'Maya@789',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Rahul Joshi',
//     'email': 'rahul.joshi@domain.com',
//     'phone': 9988776655,
//     'dateOfBirth': '21-08-1998',
//     'gender': 1,
//     'city': 'Nagpur', // ✅ Added city
//     'hobbies': ['Football', 'Reading'],
//     'password': 'Rahul@2023',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Pooja Singh',
//     'email': 'pooja.singh@yahoo.com',
//     'phone': 9056778901,
//     'dateOfBirth': '14-02-1995',
//     'gender': 0,
//     'city': 'Patna', // ✅ Added city
//     'hobbies': ['Photography', 'Gardening'],
//     'password': 'Pooja@456',
//     'isFavorite': false,
//   },
//   {
//     'name': 'Vishal Reddy',
//     'email': 'vishal.reddy@gmail.com',
//     'phone': 9023445678,
//     'dateOfBirth': '07-07-1993',
//     'gender': 1,
//     'city': 'Vijayawada', // ✅ Added city
//     'hobbies': ['Football', 'Movies'],
//     'password': 'Vishal@123',
//     'isFavorite': true,
//   },
//   {
//     'name': 'Ritika Deshmukh',
//     'email': 'ritika.deshmukh@domain.com',
//     'phone': 9876754321,
//     'dateOfBirth': '18-09-1999',
//     'gender': 0,
//     'city': 'Nashik', // ✅ Added city
//     'hobbies': ['Reading', 'Writing'],
//     'password': 'Ritika@789',
//     'isFavorite': false,
//   },
// ];
